### ISSUE TITLE
atomicAdd() undefined

### ISSUE THREAD

**Issue by ferria** [Behemyth/Soul-Engine#19]
atomicAdd() is undefined on line 376 in RayEngine.cu.  Have not made changes to the ray engine.

`atomicAdd(&(pt->x), col.x);
atomicAdd(&(pt->y), col.y);
atomicAdd(&(pt->z), col.z);`

Only the first one is marked undefined, although putting my cursor over the second two does not show a type signature.

**Comment by Behemyth** [comment]
Error highlighting is done by Visual Studio's intellisense module, which does not recognize atomicAdd() as a proper function. The NVCC compiles *.cu files , however, which recognizes it as a function.
