### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by syo** [Behemyth/Soul-Engine#22]
currently inoperable, should be a priority if we wanna get multithreading working

**Comment by Behemyth** [comment]
There use to be a fiber implementation that I used, but it was no longer being developed. On the other hand, boost is introducing a fiber implementation come its winter release. A scheduler can be built around this once it releases. More info when it arrives around December 9th

**Comment by Behemyth** [comment]
A simple implementation is working.  Continue adding features.
